"""Shrinks assets/equipment/<id>.png (1024px, ~73 MB in all) to 144px thumbnails.

The app shows equipment at 48pt, so 144px covers 3x screens; the thumbnails
come to a few MB. Metro needs static requires, so this also writes the id →
image map, src/features/library/equipmentImages.ts. Run after the source
images change.
"""
from pathlib import Path

from PIL import Image

mobile = Path(__file__).resolve().parents[2] / 'apps/mobile'
src, out = mobile / 'assets/equipment', mobile / 'assets/equipment_thumbs'
out.mkdir(exist_ok=True)

ids = []
for path in sorted(src.glob('*.png')):
    image = Image.open(path).convert('RGBA')
    image.thumbnail((144, 144), Image.LANCZOS)
    image.save(out / path.name, optimize=True)
    ids.append(path.stem)

lines = [
    '// Generated by tools/catalogue/build_equipment_thumbs.py — do not edit.',
    'import type { ImageSourcePropType } from \'react-native\';',
    '',
    '/** Equipment catalogue id → thumbnail; an item without an image is absent. */',
    'export const EQUIPMENT_IMAGES: Record<string, ImageSourcePropType> = {',
    *[f"  '{i}': require('../../../assets/equipment_thumbs/{i}.png')," for i in ids],
    '};',
    '',
]
(mobile / 'src/features/library/equipmentImages.ts').write_text('\n'.join(lines))
size = sum(p.stat().st_size for p in out.glob('*.png'))
print(f'{len(ids)} thumbnails, {size / 1e6:.1f} MB → {out}')
